return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-debug-adapter",
      "cmake-language-server",
      "delve",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "go-debug-adapter",
      "gofumpt",
      "goimports",
      "goimports-reviser",
      "golangci-lint",
      "golangci-lint-langserver",
      "golines",
      "gomodifytags",
      "gopls",
      "hadolint",
      "helm-ls",
      "impl",
      "js-debug-adapter",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "nilaway",
      "prettier",
      "prettierd",
      "shfmt",
      -- "solargraph",
      -- "erb-formatter",
      -- "erb-lint",
      -- "rubocop",
      -- "htmlbeautifier",
      "sqlfluff",
      "sqls",
      "staticcheck",
      "stylua",
      "taplo",
      "typescript-language-server",
      "vtsls",
      "vue-language-server",
      "yaml-language-server",
    },
  },
}
